"""tables

Revision ID: 9d117842a567
Revises: 
Create Date: 2022-07-03 12:43:59.568872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d117842a567'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoa',
    sa.Column('idPessoa', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('dataNascimento', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('idPessoa'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('conta',
    sa.Column('idConta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idPessoa', sa.Integer(), nullable=True),
    sa.Column('saldo', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('limiteSaqueDiario', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('flagAtivo', sa.Boolean(), nullable=False),
    sa.Column('tipoConta', sa.Integer(), nullable=True),
    sa.Column('dataCriacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idPessoa'], ['pessoa.idPessoa'], ),
    sa.PrimaryKeyConstraint('idConta')
    )
    op.create_table('transacao',
    sa.Column('idTransacao', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idConta', sa.Integer(), nullable=True),
    sa.Column('value', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('dataTransacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idConta'], ['conta.idConta'], ),
    sa.PrimaryKeyConstraint('idTransacao')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacao')
    op.drop_table('conta')
    op.drop_table('pessoa')
    # ### end Alembic commands ###
